# Site
name: "Suyash Bajpai"
title: "syPai"
description: "Disciplined & Relentless"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: "https://sypai.github.io"
# google_analytics: 'UA-46278016-1'
disqus:
  shortname: sypai-github-io
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Suyash Bajpai:
    name: Suyash Bajpai
    display_name: syPai
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: 7suyashbajpai@gmail.com
    web: https://sypai.github.io
    description: "A 3rd year undergraduate aiming to be a professional software developer."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
